# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI-CD with GitHub Actions and Bicep

on:
  # push:
  #  branches:
  #    - master
  workflow_dispatch:

env:
  RESOURCE_GROUP: MyTestApp999
  WEBAPP_NAME: js-with-bicep-and-github999

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn -f app/pom.xml clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/app/target/*.jar'

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  preview-bicep-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Resource Group
        uses: Azure/cli@v1.0.6
        with:
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: 2.34.1 # optional, default is agentazcliversion
          # Specify the script here
          inlineScript: |
            az version
            az group create -n $RESOURCE_GROUP -l westus
      - name: Preview Changes from Bicep
        uses: Azure/deployment-what-if-action@v1.0.0
        with:
          subscription: ${{ secrets.SUBSCRIPTION_ID  }} # Subscription ID
          resourceGroup: $RESOURCE_GROUP # Resource group name
          templateFile: azure-bicep-template.bicep # ARM template or Bicep file
          # parametersFile: # optional # Parameters file for the ARM template or Bicep
          # Additional parameters to be applied on the ARM template or Bicep. Multiple parameters should be separated by spaces.
          additionalParameters: webAppName=$WEBAPP_NAME # optional

  deploy-azure-bicep-dev:
    environment: dev
    needs: [preview-bicep-changes]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Resource Group
        uses: Azure/cli@v1.0.6
        with:
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: 2.34.1 # optional, default is agentazcliversion
          # Specify the script here
          inlineScript: |
            az version
            az group create -n $RESOURCE_GROUP -l westus

      - name: Deploy Bicep to Azure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: azure-bicep-template.bicep
          parameters: webAppName=${{ env.WEBAPP_NAME }}
          failOnStdErr: false
          

  deploy:
    runs-on: ubuntu-latest
    needs: deploy-azure-bicep-dev
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: $WEBAPP_NAME
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
